#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from hadamard_ca.controls import default_exact_controls
from hadamard_ca.harness import SearchConfig, SearchResult, objective_summary, run_harness


def identity_method(initial_q, initial_s, config):
    return SearchResult(
        q=initial_q,
        s=initial_s,
        evaluations=1,
        completed_restarts=1,
        restart_statistics={"requested": config.restart_count, "completed": 1, "best_restart": 0},
        best_objective=objective_summary(initial_q, initial_s),
        metadata={"kind": "identity_control"},
    )


def main() -> int:
    controls = default_exact_controls()
    out_dir = Path("results/controls")
    verify_dir = Path("results/verification")
    out_dir.mkdir(parents=True, exist_ok=True)
    verify_dir.mkdir(parents=True, exist_ok=True)

    control_payload = []
    metrics_payload = []
    for control in controls:
        metrics = run_harness(
            identity_method,
            control.q,
            control.s,
            SearchConfig(
                method_name=f"identity_control_n{control.length}",
                evaluation_budget=1,
                restart_count=1,
                seed=0,
                metadata={"control_length": control.length},
            ),
        )
        control_payload.append(
            {
                "length": control.length,
                "order": control.order,
                "q": list(control.q),
                "s": list(control.s),
                "canonical_fingerprint": control.canonical_fingerprint,
            }
        )
        metrics_payload.append(metrics)

    (out_dir / "exact_controls.json").write_text(json.dumps(control_payload, indent=2))
    lines = [
        "# Harness Validation",
        "",
        "Validated `hadamard_ca.harness.run_harness` on the default exact controls generated by exhaustive search in the same q/s coordinate system used for the frontier seed.",
        "",
    ]
    for metrics in metrics_payload:
        lines.extend(
            [
                f"## {metrics['method_name']}",
                f"- order: {metrics['order']}",
                f"- exact_hit: {metrics['exact_hit']}",
                f"- correlation_defect_support_size: {metrics['correlation_defect_support_size']}",
                f"- off_diagonal_gram_defect_support_size: {metrics['off_diagonal_gram_defect_support_size']}",
                f"- max_defect_magnitude: {metrics['max_defect_magnitude']}",
                f"- canonical_fingerprint: {metrics['canonical_fingerprint']}",
                "",
            ]
        )
    (verify_dir / "harness_validation.md").write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
