#!/usr/bin/env python3
"""Rerun or summarize the H1 startup matrix artifacts."""

from __future__ import annotations

import argparse
import csv
import json
import re
import subprocess
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
LANE_ROOT = REPO_ROOT / "results" / "concept_evolve" / "tree" / "001_packet_scout_handoff_root"
MANIFEST_PATH = LANE_ROOT / "results" / "manifests" / "startup_matrix_manifest.json"
RUNLOG_PATH = LANE_ROOT / "results" / "manifests" / "startup_runlog.jsonl"
RAW_ROOT = LANE_ROOT / "results" / "raw" / "startup"
TABLE_PATH = LANE_ROOT / "tables" / "startup_results.csv"
SUMMARY_PATH = LANE_ROOT / "tables" / "startup_summary.json"
NGSPICE_BIN = REPO_ROOT / "tools" / "ngspice-local"

DECKS = {
    "champion": LANE_ROOT
    / "netlists"
    / "champion"
    / "packet_scout_handoff"
    / "variant_01_rc_ranked_packet_gate"
    / "rc_ranked_packet_gate.cir",
    "fixed": LANE_ROOT
    / "netlists"
    / "baselines"
    / "fixed_startup_path"
    / "fixed_startup_path.cir",
    "nonaware": LANE_ROOT
    / "netlists"
    / "baselines"
    / "nonaware_multi_input_startup"
    / "nonaware_multi_input_startup.cir",
}

PARAM_RE = {
    "VLEVEL": re.compile(r"(?m)^\.param\s+VLEVEL=.*$"),
    "RATIO": re.compile(r"(?m)^\.param\s+RATIO=.*$"),
    "POL_A": re.compile(r"(?m)^\.param\s+POL_A=.*$"),
    "POL_B": re.compile(r"(?m)^\.param\s+POL_B=.*$"),
    "R_A": re.compile(r"(?m)^\.param\s+R_A=.*$"),
    "R_B": re.compile(r"(?m)^\.param\s+R_B=.*$"),
    "RAMP_MVPS": re.compile(r"(?m)^\.param\s+RAMP_MVPS=.*$"),
    "TSTOP": re.compile(r"(?m)^\.param\s+TSTOP=.*$"),
    "TRAN": re.compile(r"(?m)^\.tran\s+.*$"),
    "INCLUDE": re.compile(r'(?m)^\.include\s+(\S+)$'),
}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


def save_manifest(payload: dict) -> None:
    payload["updated_at"] = utc_now()
    MANIFEST_PATH.write_text(json.dumps(payload, indent=2) + "\n")


def select_cases(manifest: dict, case_ids: str | None) -> list[dict]:
    cases = manifest["cases"]
    if not case_ids:
        return cases
    wanted = {part.strip() for part in case_ids.split(",") if part.strip()}
    return [case for case in cases if case["case_id"] in wanted]


def select_designs(designs: str | None) -> list[str]:
    if not designs:
        return ["champion", "fixed", "nonaware"]
    chosen = [part.strip() for part in designs.split(",") if part.strip()]
    for design in chosen:
        if design not in DECKS:
            raise SystemExit(f"unknown design: {design}")
    return chosen


def absolutize_includes(text: str, deck_path: Path) -> str:
    def repl(match: re.Match[str]) -> str:
        raw = match.group(1).strip('"')
        include_path = (deck_path.parent / raw).resolve()
        return f'.include "{include_path}"'

    return PARAM_RE["INCLUDE"].sub(repl, text)


def render_netlist(design: str, case: dict) -> str:
    deck_path = DECKS[design]
    text = absolutize_includes(deck_path.read_text(), deck_path)
    replacements = {
        "VLEVEL": f".param VLEVEL={case['voltage_mv']}m",
        "RATIO": f".param RATIO={case['ratio_b_to_a']}",
        "POL_A": f".param POL_A={case['pol_a']}",
        "POL_B": f".param POL_B={case['pol_b']}",
        "R_A": f".param R_A={case['r_a_ohm']}",
        "R_B": f".param R_B={case['r_b_ohm']}",
        "RAMP_MVPS": f".param RAMP_MVPS={case['ramp_mvps']}",
        "TSTOP": f".param TSTOP={case['t_stop_s']}",
        "TRAN": f".tran {case['tran_step_s']} {case['t_stop_s']} 0 {case['tran_step_s']}",
    }
    for key, replacement in replacements.items():
        pattern = PARAM_RE[key]
        text, count = pattern.subn(replacement, text, count=1)
        if count != 1:
            raise RuntimeError(f"failed to rewrite {key} for {design} {case['case_id']}")
    header = [
        "* Auto-generated by tools/run_h1_matrix.py",
        f"* case_id={case['case_id']}",
        f"* polarity_mode={case['polarity_mode']}",
        f"* voltage_mv={case['voltage_mv']}",
        f"* ramp_mvps={case['ramp_mvps']}",
        f"* ratio_b_to_a={case['ratio_b_to_a']}",
        f"* t_stop_s={case['t_stop_s']}",
        f"* tran_step_s={case['tran_step_s']}",
    ]
    return "\n".join(header) + "\n" + text


def parse_log(log_text: str) -> dict:
    fields = {
        "startup_ok": re.search(r"startup_ok\s*=\s*([-+0-9.eE]+)", log_text),
        "t_handoff_s": re.search(r"t_handoff\s*=\s*([-+0-9.eE]+)", log_text),
        "e_backdrive_j": re.search(r"e_backdrive\s*=\s*([-+0-9.eE]+)", log_text),
        "e_ctrl_j": re.search(r"e_ctrl\s*=\s*([-+0-9.eE]+)", log_text),
        "vstore_final_v": re.search(r"vstore_final\s*=\s*([-+0-9.eE]+)", log_text),
    }
    parsed = {}
    for key, match in fields.items():
        parsed[key] = float(match.group(1)) if match else None
    return parsed


def run_case(design: str, case: dict) -> dict:
    deck_dir = DECKS[design].parent
    case_dir = RAW_ROOT / design / case["case_id"]
    case_dir.mkdir(parents=True, exist_ok=True)
    rendered_path = case_dir / f"{design}_{case['case_id']}.cir"
    log_path = case_dir / f"{design}_{case['case_id']}.log"
    json_path = case_dir / f"{design}_{case['case_id']}.json"
    rendered_path.write_text(render_netlist(design, case))
    proc = subprocess.run(
        [str(NGSPICE_BIN), "-b", "-o", str(log_path), rendered_path.name],
        cwd=deck_dir,
        capture_output=True,
        text=True,
        check=False,
    )
    parsed = parse_log(log_path.read_text())
    row = {
        "design": design,
        "case_id": case["case_id"],
        "return_code": proc.returncode,
        "status": "ok" if proc.returncode == 0 else "blocked",
        "polarity_mode": case["polarity_mode"],
        "voltage_mv": case["voltage_mv"],
        "ramp_mvps": case["ramp_mvps"],
        "ratio_b_to_a": case["ratio_b_to_a"],
        "pol_a": case["pol_a"],
        "pol_b": case["pol_b"],
        "r_a_ohm": case["r_a_ohm"],
        "r_b_ohm": case["r_b_ohm"],
        "t_stop_s": case["t_stop_s"],
        "tran_step_s": case["tran_step_s"],
        **parsed,
        "rendered_netlist": str(rendered_path.relative_to(REPO_ROOT)),
        "log_path": str(log_path.relative_to(REPO_ROOT)),
        "raw_path": None,
    }
    json_path.write_text(json.dumps(row, indent=2) + "\n")
    return row


def collect_existing() -> list[dict]:
    rows = []
    for design in ["champion", "fixed", "nonaware"]:
        design_dir = RAW_ROOT / design
        if not design_dir.exists():
            continue
        for case_dir in sorted(path for path in design_dir.iterdir() if path.is_dir()):
            json_path = case_dir / f"{design}_{case_dir.name}.json"
            if json_path.exists():
                rows.append(json.loads(json_path.read_text()))
    return rows


def write_runlog(rows: list[dict]) -> None:
    RUNLOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with RUNLOG_PATH.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps({"timestamp": utc_now(), **row}) + "\n")


def write_table(rows: list[dict]) -> None:
    TABLE_PATH.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "design",
        "case_id",
        "status",
        "return_code",
        "polarity_mode",
        "voltage_mv",
        "ramp_mvps",
        "ratio_b_to_a",
        "startup_ok",
        "t_handoff_s",
        "e_backdrive_j",
        "e_ctrl_j",
        "vstore_final_v",
        "t_stop_s",
        "tran_step_s",
        "rendered_netlist",
        "log_path",
        "raw_path",
    ]
    with TABLE_PATH.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in sorted(rows, key=lambda item: (item["design"], item["case_id"])):
            writer.writerow({key: row.get(key) for key in fieldnames})


def write_summary(rows: list[dict]) -> None:
    counts = {}
    for design in ["champion", "fixed", "nonaware"]:
        subset = [row for row in rows if row["design"] == design]
        counts[design] = {
            "total_cases": len(subset),
            "ok_cases": sum(1 for row in subset if row["status"] == "ok"),
            "startup_successes": sum(1 for row in subset if (row.get("startup_ok") or 0) >= 0.5 and row.get("t_handoff_s") is not None),
            "mixed_cases": sum(1 for row in subset if row["polarity_mode"] == "mixed"),
        }
    payload = {
        "suite": "startup_matrix_v1",
        "designs": ["champion", "fixed", "nonaware"],
        "manifest_path": str(MANIFEST_PATH.relative_to(REPO_ROOT)),
        "table_path": str(TABLE_PATH.relative_to(REPO_ROOT)),
        "runlog_path": str(RUNLOG_PATH.relative_to(REPO_ROOT)),
        "counts": counts,
        "updated_at": utc_now(),
    }
    SUMMARY_PATH.write_text(json.dumps(payload, indent=2) + "\n")


def cmd_run(args: argparse.Namespace) -> int:
    manifest = load_manifest()
    manifest["designs"] = ["champion", "fixed", "nonaware"]
    manifest["write_raw"] = True
    save_manifest(manifest)
    cases = select_cases(manifest, args.cases)
    designs = select_designs(args.designs)
    rows = []
    for design in designs:
        for case in cases:
            rows.append(run_case(design, case))
    all_rows = collect_existing()
    write_runlog(all_rows)
    write_table(all_rows)
    write_summary(all_rows)
    print(json.dumps({"ran": len(rows), "collected": len(all_rows), "cases": len(cases), "designs": designs}, indent=2))
    return 0


def cmd_summarize(_: argparse.Namespace) -> int:
    manifest = load_manifest()
    manifest["designs"] = ["champion", "fixed", "nonaware"]
    manifest["write_raw"] = True
    save_manifest(manifest)
    rows = collect_existing()
    write_runlog(rows)
    write_table(rows)
    write_summary(rows)
    print(json.dumps({"collected": len(rows), "table_path": str(TABLE_PATH.relative_to(REPO_ROOT))}, indent=2))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    run_parser = sub.add_parser("run")
    run_parser.add_argument("--cases")
    run_parser.add_argument("--designs")
    run_parser.set_defaults(func=cmd_run)

    sum_parser = sub.add_parser("summarize")
    sum_parser.set_defaults(func=cmd_summarize)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
